### PR TITLE
Fix bug introduced with Next.js 12.3.0

### PR DESCRIPTION
**Pull request by mfix-stripe**
PTAL @matv-stripe

### CODE REVIEW

**Review by matv-stripe — APPROVED** [review]

**Comment by NSpehler** [comment]
Hello,

I'm still getting the following error after upgrading this package to 0.1.8. Is this related?

```
Undefined tag: 'callout'
{% callout title="Test" %}

    at Object.load (/docs/node_modules/@markdoc/next.js/src/loader.js:150:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.loader (/docs/node_modules/@markdoc/next.js/src/loader.js:297:20)
error - ./src/pages/index.md
Error: Undefined tag: 'quick-links'
{% quick-links %}

Undefined tag: 'quick-link'
{% quick-link title="Test" /%}
```

Somehow this error only appears when using Yarn as my package manager, whereas it's working fine with NPM. Any ideas?

Thanks!

**Comment by mfix-stripe** [comment]
@NSpehler which version of Next.js are you on?

**Comment by NSpehler** [comment]
12.3.0 and I tried 12.3.1 too

**Comment by mfix-stripe** [comment]
Which version of `@markdoc/next.js` too? 🙂. I ran into this over the weekend too, and upgrading `next`, `@markdoc/next.js`, and `@markdoc/markdoc` fixed the issue.

**Comment by mfix-stripe** [comment]
@NSpehler can you please push up a reproduction of this issue? That will speed up the process a lot 🙂

**Pull request merged**
